### ISSUE TITLE
data loss in Only Office

### ISSUE THREAD

**Issue by MaaartinK** [nextcloud/documentserver_community#318]
Hello,

maybe someone can help with a bug. Apparently this problem is known for some time (4 years), but everything I find to this problem doesnt solve my situation or I am too much of a non-programmer to understand. I have asked in Nexcloud and Only Office forums, but was pointed into this direction here, the problem is supposed to be connected with the community document server. 

Nextcloud Storage Share: 27.1.5
OS: Win 10
Only Office: 8.2.4
Community Doc Server: 0.1.13
Browser: Firefox 122.0 (64-bit)
OO installation type: no clue, app was regularly installed in NC

Problem description:
The issue is concerning Only Office and/or the collaborative work on docs in Nextcloud with OO.
After working on several docs in OO (tabs are always open), data was not saved. We lost a lot of work due to NC or OO or the doc server not saving the changes / overwriting with the very first version of the doc. a backup from the host (hetzner) also didnt help. 
(affected file types were docx and xlsx)

the problem occured on one specific day and affected several documents which were open at that time (but not all / not excactly sure if all that were open), since then I limited the use because of this uncertainty, but generally working before was without problems. 

Apparently this problem is known for a long time, but I don’t find a safe solution for this anywhere, it almost seems as if it is not solved (or even ignored?) and people either dont use it because of this or resume to praying (as discussed [here](https://github.com/nextcloud/documentserver_community/issues/100) or [here](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/21)
Or here [ONLYOffice Data loss - #3 by ramesh.subbaraman](https://help.nextcloud.com/t/onlyoffice-data-loss/20586/3)
or there too [Data Loss Nextcloud <-> OnlyOffice - #8 by dev0](https://help.nextcloud.com/t/data-loss-nextcloud-onlyoffice/75992/8)

questions:
- How can we make sure, that edits are saved and data loss doesnt occur? (with constantly open tabs, with multiple people working on docs)
- is closing the tab in which was edited a reliable workaround? (as it was proposed somewhere, that changes might only then sent and saved securely)
- does saving manually per clicking on the floppy disk help anything? (as it was guessed somewhere, even though "save automatically" is enabled)
- i have enabled the force safe-function - is this enough?
- from the only office settings: what does it mean that data can be lost if working with these doc types: csv, odp, ods, odt, rtf, txt? does it mean working with these doc types is basically not possible (and we would need to use docx etc?), because data safety can't be guaranteed? 
 
I am no webmaster and no “computer person”, so it would be great if you could explain, how I can make sure this bug can be fixed.

Generally I would like to add, that we were very happy with having found NC with the OO integration, so we gladly left google. But this major problem sabotages the whole functionality of collaborative work and questions the overall usability of OO / NC and we fear we have to go back to G.... How can this be?

Your help and overall work is very much appreciated!

Hope you have a nice day

**Comment by mrbaseman** [comment]
Hi,

as a workaround I have implemented a cronjob which runs every few minutes 
`php occ documentserver:flush; php occ config:app:delete onlyoffice settings_error`

At least changes are saved to the database this way. Still remaining:
- If several people are editing the same document at the same time, they don't see the changes of the other one and they overwrite their changes each other.
- Changes are not synced on disk. To see the current version, one has to open the document online, and to download the changes, one has to save it from within OO (downloading the file in Nextcloud just returns the original version and misses all the changes made online).

**Comment by MaaartinK** [comment]
hey,
thanks for your reply.
i dont know how to implement the cronjob (as said I am not a programmer), I can try to understand but would be very insecure about this. considering the overwriting of changes this doesnt seem to be a practicable solution.
where would this cronjob be running - on my computer/my OS? so all other users still have the same problem or would need to implement the cronjob too?

thanks again for your help

**Comment by MaaartinK** [comment]
hey,
thanks for your reply.
i dont know how to implement the cronjob (as said I am not a programmer), I can try to understand but would be very insecure about this. considering the overwriting of changes this doesnt seem to be a practicable solution.
where would this cronjob be running - on my computer/my OS? so all other users still have the same problem or would need to implement the cronjob too?

i also managed to reproduce the problem by just opening a new doc (docx), left the tab open and edited it every day. (without saving manually) - after some days the doc was "replaced" with the very first version. 

thanks again for your help

**Comment by chadek** [comment]
There is (was?) a variable in onlyoffice json config to set the frequency of autosaving which is (was?) disable by default. It may have changed in more recent version. By taking a look to Onlyoffice settings it seams to me that with last documentserver_communiity version it is fine. You may try to update and see if you still have this issue

**Comment by MaaartinK** [comment]
Hello dear people,
thanks again for your advice. 
so there is this workaround with a cronjob which doesn't really do the job, because collaborative working is not possible. and I doubt (after your description) my somewhat minimal host (hetzner.com) could do this. Thanks for the hint though, but as said this would only solve the saving problem, but not the collaborative work.

the versions are and were all up to date, in the settings I don't find anything that enables autosaving (as I have tried before). and I dont know how to enter the json config of OO to look for another function (why would this crucial function be so hidden?) 
- so the problem remains. 
Is this problem connected to using win10?
Do I have to assume that everyone working with Nextcloud / Only Office uses Linux? (and it works fine)
And anyone who encountered the problem just quit using the software? (as it seems from the comments online)

thanks & cheers

**Comment by chadek** [comment]
It is not just a problem of yours, I tried it out and yes, document are not frequently saved. This is probably because onlyoffice configuration component seams to be handled by some php of this repo and default setting don't do the (expected) job.

**Comment by chadek** [comment]
[This PR](https://github.com/nextcloud/documentserver_community/pull/320) might solve this issue. If someone can test this out, it would be appreciated

**Comment by MaaartinK** [comment]
The mentioned third party host (in my case hetzner) says, they cant implement additional crons. That can apparently only be done with a self-managed nextcloud.
So. Still no solution in sight.... Is this really that complicated? Any other help...??

**Comment by chadek** [comment]
@MaaartinK I just released the 0.1.16 version. Please try it out as soon as possible and tell me if it work as expected.

**Comment by MaaartinK** [comment]
Hey,
thanks a lot for being on this! 
Where would I find the new version?

**Comment by chadek** [comment]
Sorry I just forgot to bump the app version number. It should be now be available in the [app store](https://apps.nextcloud.com/apps/documentserver_community/releases?platform=28#28). You should just need to perform an app update to get the new version.

**Comment by MaaartinK** [comment]
thanks, downloaded it. but now? i dont have the option to update online ("all apps are up to date") - do I need to do this in the desktop version (which then would update the online version)?  or is there a way to "manually" update the nextcloud?

**Comment by kintaro1981** [comment]
I tried document server 0.1.16 but when I edit a file in onlyoffice and it got saved the file is not syinced with the client.

Created a file on the webui of NC
Edited with Onlyoffice
Saved the file
Checked in the desktop client (in my case windows 3.12.2).
The file in the desktop is not updated

If I open and edit the file on the desktop after the save is overwrites the one on the server losing data.

I think the problem is that the sync to the desktop client is not initiated after the onlyoffice save action.

**Comment by kintaro1981** [comment]
or maybe something it's working... maybe they get synced to the desktop client after some minutes? like 10 minutes?

**Comment by chadek** [comment]
See [here](https://github.com/nextcloud/documentserver_community/issues/100#issuecomment-2041438968)

**Comment by chadek** [comment]
Fixed in [v0.1.16](https://github.com/nextcloud/documentserver_community/releases/tag/v0.1.16). Some configuration adjustments might still be treated in [this issue](https://github.com/nextcloud/documentserver_community/issues/100)

**Comment by MaaartinK** [comment]
I am very sorry to report that the new version does not fix the bug....

**Comment by kintaro1981** [comment]
It is strange. I’m going to try again tomorrow if in my case is still working. 

Have you waited 5 minutes after the save of the document?

**Comment by MaaartinK** [comment]
As before I had opened a test doc in which I put in new info every day, while keeping the tab open.
today the doc missed the last edits again...

**Comment by mrbaseman** [comment]
For my environment (NC 26 on Ubuntu 22.04) the recent changes have improved things. The documents are saved to disk now (so the time stamp in the file app matches the time when the most recent changes were made, and when downloading the file from the file app, they also contain the changes made online).

**Comment by chadek** [comment]
I think v0.1.16 fix this issue. If your document is always open, you might still have the old code into your web browser cache. Clearing it would probably help. As mentioned @kintaro1981 are synced every 5 minutes. If anymore concern about this issue please comment the still open duplicated [here](https://github.com/nextcloud/documentserver_community/issues/100). If this is still to much I could adjust to higher rate but by the end of month I'll close the issue and assume problem is solved

**Comment by chadek** [comment]
And to respond your original questions : 
  >  How can we make sure, that edits are saved and data loss doesnt occur? (with constantly open tabs, with multiple people working on docs)
    
v0.1.16 save documents every 5 minutes (need to clear web browser cache if opened first with older version running)
    
>    is closing the tab in which was edited a reliable workaround? (as it was proposed somewhere, that changes might only then sent and saved securely)

Closing document (meaning that every person, editing the document potentially at the same time, close the document) trigger a flush of the document to storage. 

 >   does saving manually per clicking on the floppy disk help anything? (as it was guessed somewhere, even though "save automatically" is enabled)
    i have enabled the force safe-function - is this enough?
I guess not, more generally, configuration seams not to be taken into account. I guess because web-socket are probably not working for now, which is why there is still [no "real" coediting](https://github.com/nextcloud/documentserver_community/issues/302)     
    
    from the only office settings: what does it mean that data can be lost if working with these doc types: csv, odp, ods, odt, rtf, txt? does it mean working with these doc types is basically not possible (and we would need to use docx etc?), because data safety can't be guaranteed?

document type in settings is the list of document that onlyoffice can handle.
