### ISSUE TITLE
Needs the Community Document Server app compatible with NC 32.x

### ISSUE THREAD

**Issue by ericxuo** [nextcloud/documentserver_community#363]
Hi,

I'm currently using Nextcloud 32.0.1 with ONLYOFFICE 9.11.0 but it looks like with the version 0.2.0 of the Community Document Server app, it is not possible to open any odt, ods, ... files.
It is maybe necessary to make Community Document Server compatible with NC 32.x. Or is it another issue ?

Regards.

Xuo.

**Comment by Jugosloven** [comment]
I am seeing the same issue, can't upgrade to v32 until this App is supported.
I truly hope that developers do this.

Thank you

**Comment by Glujaz** [comment]
Confirmed. I updated nextcloud, and it is not working anymore.

**Comment by Glujaz** [comment]
Ok, it is solved. I had to disable the certificate verification first, and I could reenable it again. Probably an outdated certificate, and at first connection, It was synced again with the new one.

**Comment by ericxuo** [comment]
Hi,

I've just updated to version 32.0.2 + ONLYOFFICE 9.11.0 +  Community Document Server 0.2.1 and it is still not working. Could you confirm this issue ?

Regards.

Xuo.

**Comment by Glujaz** [comment]
Refresh the cache.

On my side, everything works fine again.
