### ISSUE TITLE
unable to download and install on nextcloud 18.0.2

### ISSUE THREAD

**Issue by Fuseteam** [nextcloud/documentserver_community#98]
when i try to download and enable it i get the following error
`Error: cURL error 28: Operation timed out after 120000 milliseconds with 73322044 out of 315849196 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`
i have test this on dockernextcloud 18.0.2 and on the latest snap
it seems exclusive to the document server

**Comment by RafDeCoster** [comment]
Have you tried to install it via command line?
`occ app:install documentserver_community`

**Comment by guzzisti** [comment]
This should be fixed in Nextcloud 18.0.3:
https://github.com/nextcloud/server/pull/19439

https://nextcloud.com/changelog/#latest18

**Comment by Fuseteam** [comment]
@RafDeCoster yes i have tried through occ web

**Comment by Fuseteam** [comment]
i have now tested it in 18.0.3 docker still unable to download and install via the app store

**Comment by tutle** [comment]
same bad issue, unable to download, any manual solution to upload files on server ?

**Comment by tutle** [comment]
If I upload and unpack this file, does it fit ?
https://apps.nextcloud.com/apps/documentserver_community

**Comment by Fuseteam** [comment]
@tutle installing with `occ app:install documentserver_community` works

**Comment by tutle** [comment]
Thanks but I just have (and know..) access via filezilla

**Comment by tutle** [comment]
Where do I extract in the good folders once uploaded the  tar.gz ? Any suggestions ?
Thanks for any help

**Comment by beck2oldschool** [comment]
Same Issue here. Hosted nextcloud 18.0.3. When I try to install the App using the Webinterface, no error accours - no cURL 28 or anything else. Trying to install using occ command I get just this:

![Nextcloud 2020-03-31 092153](https://user-images.githubusercontent.com/62928618/77998271-1e781780-7331-11ea-9885-07b5cba5ab65.png)

**Comment by tutle** [comment]
it seems onlyoffice goes to darkside of the web...
https://www.reddit.com/r/selfhosted/comments/fpurk6/stop_recommending_onlyoffice/

**Comment by Fuseteam** [comment]
is this still an issue on 18.0.2? i have moved on to version 19 and no longer see this issue

**Comment by LAfricain** [comment]
I have this issue with nextcloud 22.2.7.
